"""empty message

Revision ID: 698290e6fca0
Revises: 27e5d28d1d3b
Create Date: 2026-06-19 10:58:15.199750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698290e6fca0'
down_revision: Union[str, Sequence[str], None] = '27e5d28d1d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content_html',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content_html',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
