"""add sync_error table

Revision ID: 776d692bc3cb
Revises: 5600322f26eb
Create Date: 2026-06-17 18:19:12.615719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776d692bc3cb'
down_revision: Union[str, Sequence[str], None] = '5600322f26eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_errors_notion_id'), 'sync_errors', ['notion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_errors_notion_id'), table_name='sync_errors')
    op.drop_table('sync_errors')
    # ### end Alembic commands ###
